# Sparrow fish completion
complete -c sparrow -f
complete -c sparrow -s h -l help -d "Show help"
complete -c sparrow -l tui -d "Launch terminal TUI"
complete -c sparrow -l web -d "Launch webview console"
complete -c sparrow -l json -d "NDJSON output"
complete -c sparrow -l model -d "Force specific model" -r
complete -c sparrow -l budget -d "Session budget cap" -r
complete -c sparrow -l autonomy -d "Autonomy level" -r -a "supervised trusted autonomous"
complete -c sparrow -n "__fish_use_subcommand" -a "run" -d "Execute a task"
complete -c sparrow -n "__fish_use_subcommand" -a "chat" -d "Interactive chat"
complete -c sparrow -n "__fish_use_subcommand" -a "swarm" -d "Swarm pipeline"
complete -c sparrow -n "__fish_use_subcommand" -a "schedule" -d "Schedule job"
complete -c sparrow -n "__fish_use_subcommand" -a "model" -d "Model routing"
complete -c sparrow -n "__fish_use_subcommand" -a "auth" -d "Credentials"
complete -c sparrow -n "__fish_use_subcommand" -a "agent" -d "Persistent agents"
complete -c sparrow -n "__fish_use_subcommand" -a "skills" -d "Skill library"
complete -c sparrow -n "__fish_use_subcommand" -a "mcp" -d "MCP connectors"
complete -c sparrow -n "__fish_use_subcommand" -a "checkpoint" -d "Checkpoints"
complete -c sparrow -n "__fish_use_subcommand" -a "rewind" -d "Restore snapshot"
complete -c sparrow -n "__fish_use_subcommand" -a "replay" -d "Replay transcript"
complete -c sparrow -n "__fish_use_subcommand" -a "gateway" -d "Messaging daemon"
complete -c sparrow -n "__fish_use_subcommand" -a "profile" -d "Isolated profiles"
complete -c sparrow -n "__fish_use_subcommand" -a "import" -d "Migrate from tool"
complete -c sparrow -n "__fish_use_subcommand" -a "config" -d "Edit config"
complete -c sparrow -n "__fish_use_subcommand" -a "update" -d "Self-update"
complete -c sparrow -n "__fish_use_subcommand" -a "doctor" -d "Diagnostics"
complete -c sparrow -n "__fish_use_subcommand" -a "setup" -d "Onboarding"
complete -c sparrow -n "__fish_use_subcommand" -a "learn" -d "Tutorial"
complete -c sparrow -n "__fish_use_subcommand" -a "memory" -d "Memory management"
